package pye.project.model;


import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Calender.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//

/** */
public class Calender
{
    /** */
    public int id;
    
    /** */
    public int month;
    
    /** */
    public int day;
    
    /** */
    public int hour;
    
    //private ArrayList<Restaurant> allRestaurants;
    
    /** */
    public ArrayList<Integer> availableTimeSlots(int time_low, int time_high)
    {
        ArrayList<Integer> allSlots = new ArrayList<Integer>();
        //search the database
        //find this restaurant
        //return time slots in this particular range
        
        return allSlots;
    }
    
    /** */
    public int availableSeats()
    {
    
        return 0;
    }
    
    /** */
    public int getTotalSeats()
    {
    return 0; 
    }
    
    /** */
    public int getOperatingHours()
    {
    return 0;
    }
    
    /** */
    public void reserveSeats()
    {
    
    }
}
