package pye.project.model;


import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class Customer extends Person
{
    public Customer(int personID, String lastName, String firstName,
			String email) {
		super(personID, lastName, firstName, email);
		// TODO Auto-generated constructor stub
	}

	/** */
    public void shareReservation(ArrayList<String> emailAddresses, String type)
    {
        EmailSender.sendMail(emailAddresses,null, "Participant");
        // use the email sender to share the reservation with others
    }
}
