package pye.project.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//

/** */
public class Person
{
    /** */
    private int id;
    
    /** */
    private String firstName;
    
    /** */
    private String lastName;
    
    /** */
    private String email;
    
    /** */
    
	public Person(int personID, String lastName, String firstName, String email)
	{
		super();
		this.id = personID;
		this.lastName = lastName;
		this.firstName = firstName;
		this.email = email;
	}

	/**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @return the firstName
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @return the lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

}
