package pye.project.model;

import java.sql.Date;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservation.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class Reservation
{
	DataAccess dao = new DataAccess();
    /** */
    public int id;
    
    /** */
    private int reqTime;
    
    /** */
    private Date reqDate;
    
    /** */
    public int ConfirmationNumber;
    
    /** */
    private int PartySize;
    
    /** */
    public Person CreatedBy;

	public Restaurant restaurant;
	//added restaurant object in arguments
    public Reservation(int id, int reqTime, Date reqDate, int ConfirmationNumber, int PartySize, Person CreatedBy, Restaurant restaurant) {
    	super();
    	this.id = id;
        this.reqTime = reqTime;
        this.reqDate = reqDate;
        this.ConfirmationNumber = ConfirmationNumber;
        this.PartySize = PartySize;
        this.CreatedBy = CreatedBy;
        this.restaurant = restaurant;
        
        //add it to the database
    }
        
    /** */
    public void setReservation(int reqTime, Date reqDate, int RestaurantId, int ConfirmationNumber, int PartySize, Person CreatedBy)
    {
    	dao.addReservation(CreatedBy, reqDate, reqTime, PartySize, ConfirmationNumber, RestaurantId);
    //change the object as required.
    // save the change into the database
    }
    
    /** */
    public Person getCreatedPerson()
    {
        return  CreatedBy;
    }

    /**
     * @return the PartySize
     */
    public int getPartySize() {
        return PartySize;
    }

    /**
     * @return the reqTime
     */
    public int getReqTime() {
        return reqTime;
    }

    /**
     * @return the reqDate
     */
    public Date getReqDate() {
        return reqDate;
    }
    
    public void setPartySize(int newPartySize) {
        PartySize = newPartySize;
        
        //change this in the database
    }

    /**
     * @param reqTime the reqTime to set
     */
    public void setReqTime(int reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * @param reqDate the reqDate to set
     */
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }
    

}