package pye.project.model;


import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SearchEngine.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class SearchEngine
{
    /** */
    public int id;
    
    /**  Searches the database and returns all the restaurants that fit the required parameters
    */
    public static ArrayList<Restaurant> searchRestaurants(String city, String state, int openTime, int endTime, int requiredNumberOfSeats)
    {
    //use the parameters to search the database and return an arraylist of 
        return null;
    }
    
    public static Reservation searchReservation(int ConfirmationNumber)
    {
        return null;
    }
    
     public static Restaurant searchRestaurant(int id)
    {
    //Return the restaurant whose id number is 'id'
        return null;
    }
    
}
