package pye.project.model;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SearchEngine.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class SearchEngine
{
    /** */
    public int id;
    public static DataAccess dao;
    
    /**  Searches the database and returns all the restaurants that fit the required parameters
    */
    public static ArrayList<Restaurant> searchRestaurants(String city, String reqCuisine, Date date, int reqTime, int requiredNumberOfSeats, int price)
    {
    //use the parameters to search the database and return an arraylist of 
    	
        return (dao.searchRestaurants(city, reqCuisine, reqTime, price, requiredNumberOfSeats));
    }
    
    public static Reservation searchReservation(int ConfirmationNumber) throws Exception
    {
        return (dao.searchReservation(null, ConfirmationNumber));
    }
    
     public static Restaurant searchRestaurant(int id) throws SQLException
    {
   
        return (dao.getRestaurant(id));
    }
    
}
