
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class Customer extends Person
{
    /** */
    public void shareReservation(ArrayList<String> emailAddresses, String type)
    {
        EmailSender.sendMail(emailAddresses,null, "Participant");
        // use the email sender to share the reservation with others
    }
}
