//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class Customer extends Person
{
    /** */
    public void selectRestaurant()
    {
        // uses the addReservation method to 
    }
    
    /** */
    public void shareReservation()
    {
    
        // use the email sender to share the reservation with others
    }
}
