//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailSender.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//




/** */
public class EmailSender
{
    /** */
    public int id;
    
    /** */
    public String emailAddress;
    
    /* Sends a confirmation mail to the manager about the reservation
    */
    public static void confirmation(String ManagerEmail)
    {
    
    }
    
    /** Notifies other people.
     * 
     */
    public static void notifyParticipants()
    {
    
    }
}
