
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservation.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//




/** */
public class Reservation
{
    /** */
    public int id;
    
    /** */
    public Boolean Confirmed;
    
    /** */
    public int reqTime;
    
    /** */
    public Date reqDate;
    
    /** */
    public int RestaurantId;
    
    /** */
    public int ConfirmationNumber;
    
    /** */
    public int PartySize;
    
    /** */
    public Person CreatedBy;

    public Reservation(int id, Boolean Confirmed, int reqTime, Date reqDate, int RestaurantId, int ConfirmationNumber, int PartySize, Person CreatedBy) {
        this.id = id;
        this.Confirmed = Confirmed;
        this.reqTime = reqTime;
        this.reqDate = reqDate;
        this.RestaurantId = RestaurantId;
        this.ConfirmationNumber = ConfirmationNumber;
        this.PartySize = PartySize;
        this.CreatedBy = CreatedBy;
        
        //add it to the database
    }
        
    /** */
    public void setReservation()
    {
    
    }
    
    /** */
    public void confirmReservation()
    {
        this.Confirmed = true;
    }
    
    /** */
    public Boolean getConfirmationStatus()
    {
        return Confirmed;
    }
    
    /** */
    public Person getCreatedPerson()
    {
        return  CreatedBy;
    }
}
