
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservation.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//


/** */
public class Reservation
{
    /** */
    public int id;
    
    /** */
    public Boolean Confirmed;
    
    /** */
    private int reqTime;
    
    /** */
    private Date reqDate;
    
    /** */
    public int ConfirmationNumber;
    
    /** */
    private int PartySize;
    
    /** */
    public Person CreatedBy;

    public Reservation(int id, Boolean Confirmed, int reqTime, Date reqDate, int ConfirmationNumber, int PartySize, Person CreatedBy) {
        this.id = id;
        this.Confirmed = Confirmed;
        this.reqTime = reqTime;
        this.reqDate = reqDate;
        this.ConfirmationNumber = ConfirmationNumber;
        this.PartySize = PartySize;
        this.CreatedBy = CreatedBy;
        
        //add it to the database
    }
        
    /** */
    public void setReservation(Boolean Confirmed, int reqTime, Date reqDate, int RestaurantId, int ConfirmationNumber, int PartySize, Person CreatedBy)
    {
    //change the object as required.
    // save the change into the database
    }
    
    /** */
    public void confirmReservation()
    {
        this.Confirmed = true;
    }
    
    /** */
    public Boolean getConfirmationStatus()
    {
        return Confirmed;
    }
    
    /** */
    public Person getCreatedPerson()
    {
        return  CreatedBy;
    }

    /**
     * @return the PartySize
     */
    public int getPartySize() {
        return PartySize;
    }

    /**
     * @return the reqTime
     */
    public int getReqTime() {
        return reqTime;
    }

    /**
     * @return the reqDate
     */
    public Date getReqDate() {
        return reqDate;
    }
    
    public void setPartySize(int newPartySize) {
        PartySize = newPartySize;
        
        //change this in the database
    }

    /**
     * @param reqTime the reqTime to set
     */
    public void setReqTime(int reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * @param reqDate the reqDate to set
     */
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }
    

}