
import java.util.ArrayList;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReservationManager.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//




/** */
public class ReservationManager
{
    static int RestaurantIdCurrentlySelected;
    /** */
    public static int addRestaurant()
    {
        //create a new reastaurant
        //add it to the database
    }
    
    /** */
    public static ArrayList<Restaurant> searchDatabaseForRestaurants(int id, int phoneNumber, String city, String state, int zipcode, int startTime, int endTime, String cuisine, String name, int priceLow, int priceHigh, int totalNumberOfSeats, String managerEmail)
    {
    
    }
    
    /** */
    public static void displayResultsOfSearch()
    {
    
    }
    
    /** */
    public static void bookReservationInSystem(int reqTime, Date reqDate,int ConfirmationNumber, int PartySize, Person CreatedBy)
    {
        int aNewID = 0;
        // make the reservation and add it to the database (inside the reservation class)
        Reservation aReservation = new Reservation (aNewID, false,reqTime,reqDate,RestaurantIdCurrentlySelected,ConfirmationNumber,PartySize,CreatedBy);
        //Find the restaurant manager's email address
        ArrayList<Restaurant> someRestaurant = ReservationManager.searchDatabaseForRestaurants(RestaurantIdCurrentlySelected,-1,"","", -1,-1,-1, "", "", -1, -1, -1, "");
        String ManagerEmail =  someRestaurant.get(0).getManagerEmailAddress();
        //send a confirmation to the restaurant manager
        EmailSender.confirmation(ManagerEmail); 
        
    }
    
    private void setSelectedRestaurant(int RestaurantId)
    {
        RestaurantIdCurrentlySelected = RestaurantId;
    }
    
    /** Updates or cancels a reservation 
     */
    public static int updateReservationInSystem(boolean cancel)
    { 
        //if(cancel == true)
            //cancel it
        //else update it in database
    
    }
    
            
    /** */
    private static Boolean verifyAvailabilityOfRestaurant()
    {
    
    }
    
    /** */
    public static int updateRestaurantInformation()
    {
    
    }
    
    
}
