//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SearchEngine.java
//  @ Date : 11/26/2014
//  @ Author : 
//
//




/** */
public class SearchEngine
{
    /** */
    public int id;
    
    /**  Searches the database and returns all the restaurants that fit the required parameters
    */
    public ArrayList<Restaurant> searchRestaurants()
    {
    
    }
}
